# Generated by Django 4.2.7 on 2023-12-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_patientmodel_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Physician',
            new_name='PhysicianModel',
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
