# Generated by Django 4.2.7 on 2023-12-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_physicianmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianmodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
