# Generated by Django 4.2.7 on 2023-12-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_healthcentermodel_av_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcentermodel',
            name='recent_reviews',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='physicianmodel',
            name='recent_reviews',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
