# Generated by Django 4.2.7 on 2024-01-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_healthcentermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicianmodel',
            name='hcId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='registration.healthcentermodel'),
        ),
    ]
