# Generated by Django 4.2.7 on 2023-12-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0006_healthcentermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('record', models.ImageField(blank=True, null=True, upload_to='records/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hcId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.healthcentermodel')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.patientmodel')),
                ('physicianId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.physicianmodel')),
            ],
        ),
    ]
