# Generated by Django 4.2.7 on 2023-12-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecords',
            name='record',
            field=models.FileField(blank=True, null=True, upload_to='records/'),
        ),
    ]
