# Generated by Django 4.2.7 on 2023-12-28 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatesAndReviewsModel',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=4)),
                ('review', models.TextField(max_length=400)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
