# Generated by Django 4.2.7 on 2023-12-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate_and_review', '0002_healthcenterratesandreviews_physicianratesandreviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcenterratesandreviews',
            old_name='physicianId',
            new_name='hcId',
        ),
    ]
