# Generated by Django 4.2.7 on 2023-12-28 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_healthcentermodel'),
        ('rate_and_review', '0004_alter_physicianratesandreviews_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCenterAverageRate',
            fields=[
                ('hcId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.healthcentermodel')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicianAverageRate',
            fields=[
                ('physicianId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.physicianmodel')),
                ('rate', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
