# Generated by Django 4.2.7 on 2023-12-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
