# Generated by Django 4.2.7 on 2023-12-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_physician_physicianmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
